// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package users

import (
	"context"

	"go-code/awesomeProject1/app/login_zero/rpc/types/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserInfoRequest   = user.UserInfoRequest
	UserInfoResponse  = user.UserInfoResponse
	UserLoginRequest  = user.UserLoginRequest
	UserLoginResponse = user.UserLoginResponse

	Users interface {
		UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
		UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error)
	}

	defaultUsers struct {
		cli zrpc.Client
	}
)

func NewUsers(cli zrpc.Client) Users {
	return &defaultUsers{
		cli: cli,
	}
}

func (m *defaultUsers) UserInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	client := user.NewUsersClient(m.cli.Conn())
	return client.UserInfo(ctx, in, opts...)
}

func (m *defaultUsers) UserLogin(ctx context.Context, in *UserLoginRequest, opts ...grpc.CallOption) (*UserLoginResponse, error) {
	client := user.NewUsersClient(m.cli.Conn())
	return client.UserLogin(ctx, in, opts...)
}
